force-app/main/default/objects/Case/fields/labels__c.field-meta.xml
<CustomField>
    <fullName>labels__c</fullName>
    <description>Auto created by SCMT.</description>
    <label>Assigned Labels</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/RMA_Device_Detail__c.object-meta.xml
<CustomObject>
    <label>RMA Device Detail</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RMA Device Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Device Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>RMA Device Details</relationshipLabel>
    <relationshipName>RMA_Device_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Device_Family__c.field-meta.xml
<CustomField>
    <fullName>Device_Family__c</fullName>
    <label>Device Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MYCRO</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>SENSE</fullName>
            </value>
            <value>
                <fullName>TOUCH</fullName>
            </value>
            <value>
                <fullName>SENSE2</fullName>
                <label>SENSE 2</label>
            </value>
            <value>
                <fullName>TOUCH2</fullName>
                <label>TOUCH 2</label>
            </value>
            <value>
                <fullName>TOUCH LITE</fullName>
            </value>
            <value>
                <fullName>TITAN</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>MERGE 2</fullName>
            </value>
            <value>
                <fullName>TFACE</fullName>
            </value>
            <value>
                <fullName>TITAN GEN 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Device_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Device_Serial_Number__c</fullName>
    <label>Device Serial Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Device_Family__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CR+</fullName>
            </value>
            <value>
                <fullName>CREDENCE TAB</fullName>
            </value>
            <value>
                <fullName>FP1</fullName>
            </value>
            <value>
                <fullName>FP1X</fullName>
            </value>
            <value>
                <fullName>FP2</fullName>
            </value>
            <value>
                <fullName>FP21</fullName>
            </value>
            <value>
                <fullName>FP21X</fullName>
            </value>
            <value>
                <fullName>FP22</fullName>
            </value>
            <value>
                <fullName>FP22+</fullName>
            </value>
            <value>
                <fullName>FP22W</fullName>
            </value>
            <value>
                <fullName>FP22X</fullName>
            </value>
            <value>
                <fullName>FP2X</fullName>
            </value>
            <value>
                <fullName>FP3</fullName>
            </value>
            <value>
                <fullName>FP3X</fullName>
            </value>
            <value>
                <fullName>FP4</fullName>
            </value>
            <value>
                <fullName>FP4+</fullName>
            </value>
            <value>
                <fullName>FP4X</fullName>
            </value>
            <value>
                <fullName>FP5</fullName>
            </value>
            <value>
                <fullName>FP5X</fullName>
            </value>
            <value>
                <fullName>FPL1</fullName>
            </value>
            <value>
                <fullName>FPL1X</fullName>
            </value>
            <value>
                <fullName>FPL2</fullName>
            </value>
            <value>
                <fullName>FPL21</fullName>
            </value>
            <value>
                <fullName>FPL21X</fullName>
            </value>
            <value>
                <fullName>FPL22</fullName>
            </value>
            <value>
                <fullName>FPL22X</fullName>
            </value>
            <value>
                <fullName>FPL2X</fullName>
            </value>
            <value>
                <fullName>FPL3</fullName>
            </value>
            <value>
                <fullName>FPL3X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Hardware_Issue__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Issue__c</fullName>
    <label>Defect Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACP_LED lines damaged</fullName>
            </value>
            <value>
                <fullName>Android Crash</fullName>
            </value>
            <value>
                <fullName>Audio Issue</fullName>
            </value>
            <value>
                <fullName>Battery Issue</fullName>
            </value>
            <value>
                <fullName>Boot-Up Issue</fullName>
            </value>
            <value>
                <fullName>Camera Issue</fullName>
            </value>
            <value>
                <fullName>Card Detection Issue</fullName>
            </value>
            <value>
                <fullName>Card Reader Damaged</fullName>
            </value>
            <value>
                <fullName>Crack on front-shell</fullName>
            </value>
            <value>
                <fullName>Device Database Error</fullName>
            </value>
            <value>
                <fullName>Device Hang Issue</fullName>
            </value>
            <value>
                <fullName>Door Relay Issue</fullName>
            </value>
            <value>
                <fullName>Faulty IO Cables</fullName>
            </value>
            <value>
                <fullName>Input Wiegand Line Damaged</fullName>
            </value>
            <value>
                <fullName>LCD Issues</fullName>
            </value>
            <value>
                <fullName>Mechanical Defect</fullName>
            </value>
            <value>
                <fullName>Microphone Issue</fullName>
            </value>
            <value>
                <fullName>Moist issue in Device</fullName>
            </value>
            <value>
                <fullName>NAND Corruption</fullName>
            </value>
            <value>
                <fullName>No Ethernet</fullName>
            </value>
            <value>
                <fullName>Output Wiegand Line Damaged</fullName>
            </value>
            <value>
                <fullName>Power Issue</fullName>
            </value>
            <value>
                <fullName>Proximity Sensor Defect</fullName>
            </value>
            <value>
                <fullName>Random Reboot Issue</fullName>
            </value>
            <value>
                <fullName>Sensor Issue</fullName>
            </value>
            <value>
                <fullName>Speaker Issue</fullName>
            </value>
            <value>
                <fullName>SPIO Line Damaged</fullName>
            </value>
            <value>
                <fullName>White LCD</fullName>
            </value>
            <value>
                <fullName>Physically Damaged</fullName>
            </value>
            <value>
                <fullName>EKIT Issues</fullName>
                <label>Hardware Issue with Enhancement Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMA_Device_Detail__c/fields/Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Status__c</fullName>
    <label>Warranty Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mixed Warranty</fullName>
            </value>
            <value>
                <fullName>Out of Warranty</fullName>
            </value>
            <value>
                <fullName>Under Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCaseRMAApprovalTemplt.cls
@isTest
public class TestCaseRMAApprovalTemplt {

    @isTest
    public static void testRMAApprovalMT(){
        
        Account a = new Account(name='test');
        insert a;
        
        Contact con = new Contact();
        con.lastname = 'test';
        con.AccountId = a.id;
        
        insert con;
        
        Case ca = new Case();
        ca.ContactId = con.id;
        ca.Subject = 'test';
        ca.labels__c = 'test';
        
        insert ca;
        
        RMA_Device_Detail__c rmaDevice = new RMA_Device_Detail__c();
        rmaDevice.Device_Serial_Number__c = '123';
        rmaDevice.Device_Type__c = 'FP22';
        rmaDevice.Device_Family__c = 'MYCRO';
        rmaDevice.Warranty_Status__c = 'Out of Warranty';
        rmaDevice.Hardware_Issue__c = 'Android Crash';
        rmaDevice.Case__c = ca.id;
        
        insert rmaDevice;
        Test.startTest();
            CaseRMAApprovalTemplt obj = new CaseRMAApprovalTemplt();
            obj.caseId = ca.id;
            obj.getrma();
            obj.getDeviceNumbers();
        
        SendRMAApprovalMessage.sendRMApprovalEmail(new List<Case>{ca});
        Test.stopTest();
        
    }
}